from __future__ import annotations

from collections.abc import AsyncIterator
from pathlib import Path
from typing import Protocol

from .models import BatchAnalysis, CapturedFrame


class RobotPort(Protocol):
    @property
    def connected(self) -> bool: ...

    @property
    def last_playback_started_at(self) -> float | None: ...

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def warmup_camera(self) -> None: ...
    async def capture(
        self, destination: Path, frame_id: str, sequence: int
    ) -> CapturedFrame: ...
    async def microphone_chunks(self) -> AsyncIterator[bytes]: ...
    async def play_pcm(self, chunks: AsyncIterator[bytes]) -> None: ...
    async def stop_audio(self) -> None: ...
    async def play_animation(self, animation_id: str) -> bool: ...
    async def play_behavior(self, behavior_id: str) -> bool: ...
    async def enter_focus_mode(self) -> bool: ...


class VisionPort(Protocol):
    async def analyze(self, frames: list[CapturedFrame]) -> BatchAnalysis: ...
    async def health(self) -> bool: ...


class AsrPort(Protocol):
    async def transcribe(self, pcm: bytes) -> str: ...
    async def health(self) -> bool: ...


class LlmPort(Protocol):
    async def reply(self, text: str, *, max_chinese_chars: int = 60) -> str: ...
    async def health(self) -> bool: ...


class TtsPort(Protocol):
    def synthesize(self, text: str) -> AsyncIterator[bytes]: ...
    async def health(self) -> bool: ...
